const 
  SOF0_MARKER  = 0xFFC0'u16 # Start of Frame 0 (Baseline DCT)
  SOF1_MARKER  = 0xFFC1'u16 # Start of Frame 1 (Extended Sequential DCT)
  SOF2_MARKER  = 0xFFC2'u16 # Start of Frame 2 (Progressive DCT)
  SOF3_MARKER  = 0xFFC3'u16 # Start of Frame 3 (Lossless (sequential))
  DHT_MARKER   = 0xFFC4'u16 # Define Huffman Table
  SOF5_MARKER  = 0xFFC5'u16 # Start of Frame 5 (Differential sequential DCT)
  SOF6_MARKER  = 0xFFC6'u16 # Start of Frame 6 (Differential progressive DCT)
  SOF7_MARKER  = 0xFFC7'u16 # Start of Frame 7 (Differential lossless (sequential))
  JPG_MARKER   = 0xFFC8'u16 # JPEG Extensions
  SOF9_MARKER  = 0xFFC9'u16 # Start of Frame 9 (Extended sequential DCT, Arithmetic coding)
  SOF10_MARKER = 0xFFCA'u16 # Start of Frame 10 (Progressive DCT, Arithmetic coding)
  SOF11_MARKER = 0xFFCB'u16 # Start of Frame 11 (Lossless (sequential), Arithmetic coding)
  DAC_MARKER   = 0xFFCC'u16 # Define Arithmetic Coding
  SOF13_MARKER = 0xFFCD'u16 # Start of Frame 13 (Differential sequential DCT, Arithmetic coding)
  SOF14_MARKER = 0xFFCE'u16 # Start of Frame 14 (Differential progressive DCT, Arithmetic coding)
  SOF15_MARKER = 0xFFCF'u16 # Start of Frame 15 (Differential lossless (sequential), Arithmetic coding)
  RST0_MARKER  = 0xFFD0'u16 # Restart Marker 0
  RST1_MARKER  = 0xFFD1'u16 # Restart Marker 1
  RST2_MARKER  = 0xFFD2'u16 # Restart Marker 2
  RST3_MARKER  = 0xFFD3'u16 # Restart Marker 3
  RST4_MARKER  = 0xFFD4'u16 # Restart Marker 4
  RST5_MARKER  = 0xFFD5'u16 # Restart Marker 5
  RST6_MARKER  = 0xFFD6'u16 # Restart Marker 6
  RST7_MARKER  = 0xFFD7'u16 # Restart Marker 7
  SOI_MARKER   = 0xFFD8'u16 # Start of Image
  EOI_MARKER   = 0xFFD9'u16 # End of Image
  SOS_MARKER   = 0xFFDA'u16 # Start of Scan
  DQT_MARKER   = 0xFFDB'u16 # Define Quantization Table
  DNL_MARKER   = 0xFFDC'u16 # Define Number of Lines (Not common)
  DRI_MARKER   = 0xFFDD'u16 # Define Restart Interval
  DHP_MARKER   = 0xFFDE'u16 # Define Hierarchical Progression (Not common)
  EXP_MARKER   = 0xFFDF'u16 # Expand Reference Component (Not common)
  APP0_MARKER  = 0xFFE0'u16 # Application Segment 0 (JFIF – JFIF JPEG image, AVI1 – Motion JPEG (MJPG))
  APP1_MARKER  = 0xFFE1'u16 # Application Segment 1 (EXIF Metadata, JPEG Thumbnail)
  APP2_MARKER  = 0xFFE2'u16 # Application Segment 2 (ICC color profile, FlashPix)
  APP3_MARKER  = 0xFFE3'u16 # Application Segment 3 (Not common, JPS Tag for Stereoscopic JPEG images)
  APP4_MARKER  = 0xFFE4'u16 # Application Segment 4 (Not common)
  APP5_MARKER  = 0xFFE5'u16 # Application Segment 5 (Not common)
  APP6_MARKER  = 0xFFE6'u16 # Application Segment 6 (Not common, NITF Lossless profile)
  APP7_MARKER  = 0xFFE7'u16 # Application Segment 7 (Not common)
  APP8_MARKER  = 0xFFE8'u16 # Application Segment 8 (Not common)
  APP9_MARKER  = 0xFFE9'u16 # Application Segment 9 (Not common)
  APP10_MARKER = 0xFFEA'u16 # Application Segment 10 (Not common, ActiveObject (multimedia messages/captions))
  APP11_MARKER = 0xFFEB'u16 # Application Segment 11 (Not common, HELIOS JPEG Resources (OPI Postscript))
  APP12_MARKER = 0xFFEC'u16 # Application Segment 12 (Picture Info for older digicams, Photoshop Save for Web: Ducky)
  APP13_MARKER = 0xFFED'u16 # Application Segment 13 (Photoshop Save As: IRB, 8BIM, IPTC)
  APP14_MARKER = 0xFFEE'u16 # Application Segment 14 (Not common)
  APP15_MARKER = 0xFFEF'u16 # Application Segment 15 (Not common)
  JPG0_MARKER  = 0xFFF0'u16 # JPEG Extension 0 (Not Common)
  JPG1_MARKER  = 0xFFF1'u16 # JPEG Extension 1 (Not Common)
  JPG2_MARKER  = 0xFFF2'u16 # JPEG Extension 2 (Not Common)
  JPG3_MARKER  = 0xFFF3'u16 # JPEG Extension 3 (Not Common)
  JPG4_MARKER  = 0xFFF4'u16 # JPEG Extension 4 (Not Common)
  JPG5_MARKER  = 0xFFF5'u16 # JPEG Extension 5 (Not Common)
  JPG6_MARKER  = 0xFFF6'u16 # JPEG Extension 6 (Not Common)
  JPG7_MARKER  = 0xFFF7'u16 # JPEG Extension 7 (JPEG-LS, Lossless JPEG)
  JPG8_MARKER  = 0xFFF8'u16 # JPEG Extension 8 (JPEG-LS Extension, Lossless JPEG Extension Parameters)
  JPG9_MARKER  = 0xFFF9'u16 # JPEG Extension 9 (Not Common)
  JPG10_MARKER = 0xFFFA'u16 # JPEG Extension 10 (Not Common)
  JPG11_MARKER = 0xFFFB'u16 # JPEG Extension 11 (Not Common)
  JPG12_MARKER = 0xFFFC'u16 # JPEG Extension 12 (Not Common)
  JPG13_MARKER = 0xFFFD'u16 # JPEG Extension 13 (Not Common)
  COM_MARKER   = 0xFFFE'u16 # Comment